# This rule is not used by the project klease itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over klease.zachallen.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: klease
    app.kubernetes.io/managed-by: kustomize
  name: gpulease-admin-role
rules:
- apiGroups:
  - klease.zachallen.io
  resources:
  - gpuleases
  verbs:
  - '*'
- apiGroups:
  - klease.zachallen.io
  resources:
  - gpuleases/status
  verbs:
  - get
