---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klease.zachallen.io
  resources:
  - gpuleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klease.zachallen.io
  resources:
  - gpuleases/finalizers
  verbs:
  - update
- apiGroups:
  - klease.zachallen.io
  resources:
  - gpuleases/status
  verbs:
  - get
  - patch
  - update
